# Välj Node.js som basimage
FROM node:latest

# Skapa och sätt arbetsmappen
WORKDIR /api

# Kopiera API-serverns filer till containern
COPY . /api

# Installera API-serverns beroenden
RUN npm install

# Exponera porten som din API-server använder (om tillämpligt)
# Ersätt 'YYYY' med den faktiska porten som används av din API-server
EXPOSE 5050

# Starta API-servern
CMD ["node", "server.mjs"]